apiVersion: v2
name: cms-grafana
description: Aliyun CMS Grafana Dashboard
type: application
version: 0.4.2
appVersion: 7.1.0
keywords:
- grafana
- aliyun
- cms
icon: https://raw.githubusercontent.com/grafana/grafana/master/docs/logo-horizontal.png
sources:
- https://github.com/sunny0826/cms-grafana-builder
maintainers:
- name: GuoXudong
  email: sunnydog0826@gmail.com

